# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GR_Qt_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GR_Qt(object):
    def setupUi(self, GR_Qt):
        GR_Qt.setObjectName("GR_Qt")
        GR_Qt.setWindowModality(QtCore.Qt.WindowModal)
        GR_Qt.setEnabled(True)
        GR_Qt.resize(870, 375)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GR_Qt.sizePolicy().hasHeightForWidth())
        GR_Qt.setSizePolicy(sizePolicy)
        GR_Qt.setMinimumSize(QtCore.QSize(870, 375))
        GR_Qt.setMaximumSize(QtCore.QSize(870, 375))
        GR_Qt.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(GR_Qt)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(630, 20, 221, 121))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 201, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Cam_Open = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cam_Open.setObjectName("Cam_Open")
        self.verticalLayout.addWidget(self.Cam_Open)
        self.Cam_Close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cam_Close.setObjectName("Cam_Close")
        self.verticalLayout.addWidget(self.Cam_Close)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 250, 221, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Reco_Start = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Reco_Start.setObjectName("Reco_Start")
        self.horizontalLayout_2.addWidget(self.Reco_Start)
        self.Reco_Stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Reco_Stop.setObjectName("Reco_Stop")
        self.horizontalLayout_2.addWidget(self.Reco_Stop)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 341, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.HandPose = QtWidgets.QLabel(self.groupBox_3)
        self.HandPose.setGeometry(QtCore.QRect(20, 20, 310, 300))
        self.HandPose.setText("")
        self.HandPose.setPixmap(QtGui.QPixmap("data/train/pose/gesture_1.8.jpg"))
        self.HandPose.setObjectName("HandPose")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 10, 261, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.Del_Log = QtWidgets.QPushButton(self.groupBox_4)
        self.Del_Log.setGeometry(QtCore.QRect(10, 290, 241, 28))
        self.Del_Log.setObjectName("Del_Log")
        self.Log_Widget = QtWidgets.QListWidget(self.groupBox_4)
        self.Log_Widget.setGeometry(QtCore.QRect(10, 20, 241, 261))
        self.Log_Widget.setObjectName("Log_Widget")
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Log_Widget.addItem(item)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(630, 150, 221, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.Result_Label = QtWidgets.QLabel(self.groupBox_5)
        self.Result_Label.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.Result_Label.setObjectName("Result_Label")
        GR_Qt.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GR_Qt)
        self.statusbar.setObjectName("statusbar")
        GR_Qt.setStatusBar(self.statusbar)

        self.retranslateUi(GR_Qt)
        QtCore.QMetaObject.connectSlotsByName(GR_Qt)

    def retranslateUi(self, GR_Qt):
        _translate = QtCore.QCoreApplication.translate
        GR_Qt.setWindowTitle(_translate("GR_Qt", "基于Qt的手势识别系统"))
        self.groupBox.setTitle(_translate("GR_Qt", "摄像头控制"))
        self.Cam_Open.setText(_translate("GR_Qt", "开启"))
        self.Cam_Close.setText(_translate("GR_Qt", "关闭"))
        self.groupBox_2.setTitle(_translate("GR_Qt", "实时识别"))
        self.Reco_Start.setText(_translate("GR_Qt", "开始"))
        self.Reco_Stop.setText(_translate("GR_Qt", "暂停"))
        self.groupBox_3.setTitle(_translate("GR_Qt", "手势关键点照片"))
        self.groupBox_4.setTitle(_translate("GR_Qt", "历史识别结果"))
        self.Del_Log.setText(_translate("GR_Qt", "删除历史结果"))
        __sortingEnabled = self.Log_Widget.isSortingEnabled()
        self.Log_Widget.setSortingEnabled(False)
        item = self.Log_Widget.item(0)
        item.setText(_translate("GR_Qt", "时间：[16:22:38]；结果：1号"))
        item = self.Log_Widget.item(1)
        item.setText(_translate("GR_Qt", "时间：[16:26:55]；结果：2号"))
        item = self.Log_Widget.item(2)
        item.setText(_translate("GR_Qt", "时间：[16:27:46]；结果：3号"))
        item = self.Log_Widget.item(3)
        item.setText(_translate("GR_Qt", "时间：[16:28:05]；结果：4号"))
        item = self.Log_Widget.item(4)
        item.setText(_translate("GR_Qt", "时间：[16:28:36]；结果：5号"))
        item = self.Log_Widget.item(5)
        item.setText(_translate("GR_Qt", "时间：[16:30:22]；结果：3号"))
        item = self.Log_Widget.item(6)
        item.setText(_translate("GR_Qt", "时间：[16:31:05]；结果：1号"))
        self.Log_Widget.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("GR_Qt", "实时识别结果"))
        self.Result_Label.setText(_translate("GR_Qt", "当前结果编号：1号"))

